# Site settings
title: Learn Programming with Java
email: Tobias.Hanf@mailbox.tu-dresden.de
description: >
  Page for the course Learn Programming with Java
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://t-hanf.github.io/" # the base hostname & protocol for your site
codepath: "code/"
# twitter_username: jekyllrb
github_username: t-hanf

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .c9/
  - .git/
  - latex/

defaults:
  -
    scope:
      path: ""
      type: "units"
    values:
      layout: "unit"

collections:
  units:
    output: true
  code:
    output: false
  pdfs:
    output: false

