# Site settings
title: Java Lesson Exercises
email: mail@tobias-hanf.de
description: >
  Rendered exercise descriptions for the java lessons
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://t-hanf.github.io/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: t-hanf

# Build settings
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - .c9/
  - .git/
  - latex/

defaults:
  -
    scope:
      path: ""
      type: "exercises"
    values:
      layout: "exercise"

collections:
  exercises:
    output: true
